# Generated by Django 2.2.4 on 2019-12-10 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gut_matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gutmatrix',
            name='gravity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
