# Generated by Django 2.2.4 on 2019-12-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gut_matrix', '0003_auto_20191210_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gutmatrix',
            name='updated_at',
        ),
    ]
