# Generated by Django 2.2.4 on 2019-12-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gut_matrices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=5000)),
                ('requester', models.CharField(max_length=70)),
                ('requester_email', models.EmailField(max_length=254)),
                ('origin', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('ABERTA', 'ABERTA'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('FECHADA', 'FECHADA')], default='ABERTA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gut_matrix', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gut_matrix', to='gut_matrices.GutMatrix')),
            ],
            options={
                'ordering': ['-gut_matrix__gut', '-created_at'],
            },
        ),
    ]
