# Generated by Django 2.2.4 on 2019-10-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='status',
            field=models.IntegerField(choices=[(1, 'ABERTA'), (2, 'FECHADA')], default=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
