# Generated by Django 2.2.4 on 2019-10-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_auto_20191028_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('FECHADA', 'FECHADA')], default='ABERTA', max_length=20),
        ),
    ]
