# Generated by Django 2.2.4 on 2019-11-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0004_auto_20191028_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='demand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='origin',
            field=models.TextField(max_length=5000),
        ),
    ]
