# Generated by Django 2.2.4 on 2019-12-10 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0005_auto_20191106_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='requester_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
