# Generated by Django 2.2.4 on 2019-12-11 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gut_matrix', '0003_auto_20191210_2050'),
        ('demands', '0006_demand_requester_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ['-gut_matrix__gut', '-created_at']},
        ),
        migrations.AddField(
            model_name='demand',
            name='gut_matrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gut_matrix', to='gut_matrix.GutMatrix'),
        ),
    ]
