# Generated by Django 2.2.4 on 2019-12-11 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0010_auto_20191211_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='gut_matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gut_matrix', to='gut_matrix.GutMatrix'),
        ),
    ]
