# Generated by Django 2.2.4 on 2019-12-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0012_auto_20191211_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='updated_at',
        ),
    ]
