# Generated by Django 2.2.4 on 2019-12-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='demand', to='demands.Demand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
