# Generated by Django 2.2.4 on 2019-12-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening_terms', '0002_openingterm_opening_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingterm',
            name='opening_term',
            field=models.FileField(upload_to=''),
        ),
    ]
